version: "3.8"
services:
  db:
    image: postgres:15
    container_name: trello_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trellodb
    ports:
      - "5433:5432" # <--- CHANGE THIS LINE (Was "5432:5432")
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data

volumes:
  postgres_data_v2:
